# This workflow deploys the React Tetris game to GitHub Pages when code is pushed to the main branch
# It builds the project using Vite and publishes the static files to the gh-pages branch
name: Deploy to GitHub Pages

# Triggers: This workflow runs when code is pushed to the main branch
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permissions needed for the deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Only allow one deployment at a time to prevent conflicts
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job: Compiles the React app
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      # Install project dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build the project for production
      # The base path must match your repository name for GitHub Pages
      - name: Build project
        run: |
          # Set the base URL to match the GitHub Pages URL structure
          # Replace 'react-minimal-tetris' with your actual repository name
          yarn build --base=/react-minimal-tetris/

      # Upload the built files as an artifact for the deploy job
      - name: Upload production build
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the Vite build output directory
          path: ./dist

  # Deploy job: Publishes the built files to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
